classes:
- service.docker.host
- system.salt.minion.cert.etcd_server_single
- service.etcd.server.single
- system.linux.system.repo.docker
- system.kubernetes.master.single
- system.kubernetes.pool.single
parameters:
  _params:
    single_address: 192.168.122.194
  etcd:
    server:
      bind:
        host: 192.168.122.194
      source:
        engine: docker_hybrid
      ssl:
        enabled: true
      setup:
        calico:
           key: /calico/v1/ipam/v4/pool/${_param:calico_private_network}-${_param:calico_private_netmask}
           value: '{"masquerade":true,"cidr":"${_param:calico_private_network}/${_param:calico_private_netmask}"}'

  kubernetes:
    pool:
      kubelet:
        address: 192.168.122.194
      network:
        etcd:
          ssl:
            enabled: true
        image: ${_param:kubernetes_calico_image}
        calicoctl:
          image: ${_param:kubernetes_calicoctl_image}
        cni:
          image: ${_param:kubernetes_calico_cni_image}
    common:
      addons:
        virtlet:
          enabled: ${_param:kubernetes_virtlet_enabled}
          namespace: ${_param:kubernetes_addon_namespace}
          image: ${_param:kubernetes_virtlet_image}
          hosts:
          - kube01
      hyperkube:
        image: ${_param:kubernetes_hyperkube_image}
    master:
      kubelet:
        address: 192.168.122.194
      etcd:
        ssl:
          enabled: true
      network:
        etcd:
          ssl:
            enabled: true
      namespace:
        netchecker:
          enabled: true

  docker:
    host:
      pkgs:
        - ${_param:kubernetes_docker_package}
        - python-docker
      options:
        bip: 172.31.255.1/24
        storage-driver: overlay2
